site_name: Docuty Docs
theme:
  name: material
  logo: assets/logo.png
  favicon: images/favicon.png
  palette:
    primary: green
copyright: <a href="https://www.lufinity.se/" target="_blank">Lufinity IT Services AB</a>